name: Flake8 Lint Check

on:
  pull_request:
    types: [opened, synchronize, edited]
  push:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8  # You can choose the Python version

    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run flake8
      run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127
