name: Unit Tests

on:
  pull_request:
    types: [opened, synchronize, edited]
  push:
    branches:
      - 'main'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}

    - name: Install graph-tool
      uses: myci-actions/add-deb-repo@10
      with:
        repo: deb [ arch=amd64 ] https://downloads.skewed.de/apt $(lsb_release -cs) main
        repo-name: skewed
        keys-asc: https://keys.openpgp.org/vks/v1/by-fingerprint/793CEFE14DBC851A2BFB1222612DEFB798507F25
        install: python3-graph-tool

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install .[meka,keras,gpl,test]
        pip install 'openne @ git+https://github.com/thunlp/OpenNE.git@master#subdirectory=src'

    - name: Run Tests
      run: pytest
